-- liquibase formatted sql

-- changeset city:061-seed-nationalites runOnChange:false splitStatements:false
-- preconditions onFail:HALT onError:HALT
-- precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM core.donnees_referentielles WHERE categorie = 'nationalite'
--
-- Seed exhaustif des nationalités (ISO 3166-1 alpha-2, 249 pays).
-- Catégorie 'nationalite' dans core.donnees_referentielles.
--
-- Idempotence : la precondition vérifie qu'aucune nationalite n'existe déjà.
-- Si la table en contient déjà au moins une, le changeset est skipped (HALT).
-- Pour ajouter des nationalités après coup, créer un nouveau changeset.
--
-- Libellés FR : nom officiel court du pays (FR).
-- Libellés EN : nom officiel court (EN).
-- Libellés AR : libellé arabe pour les pays arabes principaux + Mauritanie.
--               Pour les autres pays, le libellé AR vaut le libellé FR (fallback
--               documenté §0.6 cityfrontend CLAUDE.md, sync ultérieure possible).
-- Ordre : 0 (tri alphabétique par libelle côté repository).

INSERT INTO core.donnees_referentielles (categorie, code, libelle, libelle_en, libelle_ar, ordre_affichage, actif) VALUES
('nationalite', 'AF', 'Afghanistan', 'Afghanistan', 'أفغانستان', 0, true),
('nationalite', 'ZA', 'Afrique du Sud', 'South Africa', 'جنوب أفريقيا', 0, true),
('nationalite', 'AL', 'Albanie', 'Albania', 'ألبانيا', 0, true),
('nationalite', 'DZ', 'Algérie', 'Algeria', 'الجزائر', 0, true),
('nationalite', 'DE', 'Allemagne', 'Germany', 'ألمانيا', 0, true),
('nationalite', 'AD', 'Andorre', 'Andorra', 'أندورا', 0, true),
('nationalite', 'AO', 'Angola', 'Angola', 'أنغولا', 0, true),
('nationalite', 'AI', 'Anguilla', 'Anguilla', 'أنغويلا', 0, true),
('nationalite', 'AQ', 'Antarctique', 'Antarctica', 'القارة القطبية الجنوبية', 0, true),
('nationalite', 'AG', 'Antigua-et-Barbuda', 'Antigua and Barbuda', 'أنتيغوا وباربودا', 0, true),
('nationalite', 'SA', 'Arabie saoudite', 'Saudi Arabia', 'المملكة العربية السعودية', 0, true),
('nationalite', 'AR', 'Argentine', 'Argentina', 'الأرجنتين', 0, true),
('nationalite', 'AM', 'Arménie', 'Armenia', 'أرمينيا', 0, true),
('nationalite', 'AW', 'Aruba', 'Aruba', 'أروبا', 0, true),
('nationalite', 'AU', 'Australie', 'Australia', 'أستراليا', 0, true),
('nationalite', 'AT', 'Autriche', 'Austria', 'النمسا', 0, true),
('nationalite', 'AZ', 'Azerbaïdjan', 'Azerbaijan', 'أذربيجان', 0, true),
('nationalite', 'BS', 'Bahamas', 'Bahamas', 'جزر البهاما', 0, true),
('nationalite', 'BH', 'Bahreïn', 'Bahrain', 'البحرين', 0, true),
('nationalite', 'BD', 'Bangladesh', 'Bangladesh', 'بنغلاديش', 0, true),
('nationalite', 'BB', 'Barbade', 'Barbados', 'بربادوس', 0, true),
('nationalite', 'BE', 'Belgique', 'Belgium', 'بلجيكا', 0, true),
('nationalite', 'BZ', 'Belize', 'Belize', 'بليز', 0, true),
('nationalite', 'BJ', 'Bénin', 'Benin', 'بنين', 0, true),
('nationalite', 'BM', 'Bermudes', 'Bermuda', 'برمودا', 0, true),
('nationalite', 'BT', 'Bhoutan', 'Bhutan', 'بوتان', 0, true),
('nationalite', 'BY', 'Biélorussie', 'Belarus', 'بيلاروسيا', 0, true),
('nationalite', 'BO', 'Bolivie', 'Bolivia', 'بوليفيا', 0, true),
('nationalite', 'BA', 'Bosnie-Herzégovine', 'Bosnia and Herzegovina', 'البوسنة والهرسك', 0, true),
('nationalite', 'BW', 'Botswana', 'Botswana', 'بوتسوانا', 0, true),
('nationalite', 'BR', 'Brésil', 'Brazil', 'البرازيل', 0, true),
('nationalite', 'BN', 'Brunei', 'Brunei', 'بروناي', 0, true),
('nationalite', 'BG', 'Bulgarie', 'Bulgaria', 'بلغاريا', 0, true),
('nationalite', 'BF', 'Burkina Faso', 'Burkina Faso', 'بوركينا فاسو', 0, true),
('nationalite', 'BI', 'Burundi', 'Burundi', 'بوروندي', 0, true),
('nationalite', 'KH', 'Cambodge', 'Cambodia', 'كمبوديا', 0, true),
('nationalite', 'CM', 'Cameroun', 'Cameroon', 'الكاميرون', 0, true),
('nationalite', 'CA', 'Canada', 'Canada', 'كندا', 0, true),
('nationalite', 'CV', 'Cap-Vert', 'Cape Verde', 'الرأس الأخضر', 0, true),
('nationalite', 'CL', 'Chili', 'Chile', 'تشيلي', 0, true),
('nationalite', 'CN', 'Chine', 'China', 'الصين', 0, true),
('nationalite', 'CY', 'Chypre', 'Cyprus', 'قبرص', 0, true),
('nationalite', 'CO', 'Colombie', 'Colombia', 'كولومبيا', 0, true),
('nationalite', 'KM', 'Comores', 'Comoros', 'جزر القمر', 0, true),
('nationalite', 'CG', 'Congo', 'Congo', 'الكونغو', 0, true),
('nationalite', 'CD', 'Congo (RDC)', 'Congo (DRC)', 'جمهورية الكونغو الديمقراطية', 0, true),
('nationalite', 'KP', 'Corée du Nord', 'North Korea', 'كوريا الشمالية', 0, true),
('nationalite', 'KR', 'Corée du Sud', 'South Korea', 'كوريا الجنوبية', 0, true),
('nationalite', 'CR', 'Costa Rica', 'Costa Rica', 'كوستاريكا', 0, true),
('nationalite', 'CI', 'Côte d''Ivoire', 'Ivory Coast', 'ساحل العاج', 0, true),
('nationalite', 'HR', 'Croatie', 'Croatia', 'كرواتيا', 0, true),
('nationalite', 'CU', 'Cuba', 'Cuba', 'كوبا', 0, true),
('nationalite', 'CW', 'Curaçao', 'Curaçao', 'Curaçao', 0, true),
('nationalite', 'DK', 'Danemark', 'Denmark', 'الدنمارك', 0, true),
('nationalite', 'DJ', 'Djibouti', 'Djibouti', 'جيبوتي', 0, true),
('nationalite', 'DM', 'Dominique', 'Dominica', 'دومينيكا', 0, true),
('nationalite', 'EG', 'Égypte', 'Egypt', 'مصر', 0, true),
('nationalite', 'SV', 'Salvador', 'El Salvador', 'السلفادور', 0, true),
('nationalite', 'AE', 'Émirats arabes unis', 'United Arab Emirates', 'الإمارات العربية المتحدة', 0, true),
('nationalite', 'EC', 'Équateur', 'Ecuador', 'الإكوادور', 0, true),
('nationalite', 'ER', 'Érythrée', 'Eritrea', 'إريتريا', 0, true),
('nationalite', 'ES', 'Espagne', 'Spain', 'إسبانيا', 0, true),
('nationalite', 'EE', 'Estonie', 'Estonia', 'إستونيا', 0, true),
('nationalite', 'SZ', 'Eswatini', 'Eswatini', 'إسواتيني', 0, true),
('nationalite', 'US', 'États-Unis', 'United States', 'الولايات المتحدة', 0, true),
('nationalite', 'ET', 'Éthiopie', 'Ethiopia', 'إثيوبيا', 0, true),
('nationalite', 'FJ', 'Fidji', 'Fiji', 'فيجي', 0, true),
('nationalite', 'FI', 'Finlande', 'Finland', 'فنلندا', 0, true),
('nationalite', 'FR', 'France', 'France', 'فرنسا', 0, true),
('nationalite', 'GA', 'Gabon', 'Gabon', 'الغابون', 0, true),
('nationalite', 'GM', 'Gambie', 'Gambia', 'غامبيا', 0, true),
('nationalite', 'GE', 'Géorgie', 'Georgia', 'جورجيا', 0, true),
('nationalite', 'GH', 'Ghana', 'Ghana', 'غانا', 0, true),
('nationalite', 'GI', 'Gibraltar', 'Gibraltar', 'جبل طارق', 0, true),
('nationalite', 'GR', 'Grèce', 'Greece', 'اليونان', 0, true),
('nationalite', 'GD', 'Grenade', 'Grenada', 'غرينادا', 0, true),
('nationalite', 'GL', 'Groenland', 'Greenland', 'غرينلاند', 0, true),
('nationalite', 'GP', 'Guadeloupe', 'Guadeloupe', 'Guadeloupe', 0, true),
('nationalite', 'GU', 'Guam', 'Guam', 'غوام', 0, true),
('nationalite', 'GT', 'Guatemala', 'Guatemala', 'غواتيمالا', 0, true),
('nationalite', 'GG', 'Guernesey', 'Guernsey', 'غيرنزي', 0, true),
('nationalite', 'GN', 'Guinée', 'Guinea', 'غينيا', 0, true),
('nationalite', 'GQ', 'Guinée équatoriale', 'Equatorial Guinea', 'غينيا الاستوائية', 0, true),
('nationalite', 'GW', 'Guinée-Bissau', 'Guinea-Bissau', 'غينيا بيساو', 0, true),
('nationalite', 'GY', 'Guyana', 'Guyana', 'غيانا', 0, true),
('nationalite', 'GF', 'Guyane française', 'French Guiana', 'غويانا الفرنسية', 0, true),
('nationalite', 'HT', 'Haïti', 'Haiti', 'هايتي', 0, true),
('nationalite', 'HN', 'Honduras', 'Honduras', 'هندوراس', 0, true),
('nationalite', 'HK', 'Hong Kong', 'Hong Kong', 'هونغ كونغ', 0, true),
('nationalite', 'HU', 'Hongrie', 'Hungary', 'المجر', 0, true),
('nationalite', 'IM', 'Île de Man', 'Isle of Man', 'جزيرة مان', 0, true),
('nationalite', 'CX', 'Île Christmas', 'Christmas Island', 'جزيرة عيد الميلاد', 0, true),
('nationalite', 'NF', 'Île Norfolk', 'Norfolk Island', 'جزيرة نورفولك', 0, true),
('nationalite', 'KY', 'Îles Caïmans', 'Cayman Islands', 'جزر كايمان', 0, true),
('nationalite', 'CC', 'Îles Cocos', 'Cocos Islands', 'جزر كوكوس', 0, true),
('nationalite', 'CK', 'Îles Cook', 'Cook Islands', 'جزر كوك', 0, true),
('nationalite', 'FO', 'Îles Féroé', 'Faroe Islands', 'جزر فارو', 0, true),
('nationalite', 'FK', 'Îles Malouines', 'Falkland Islands', 'جزر فوكلاند', 0, true),
('nationalite', 'MP', 'Îles Mariannes du Nord', 'Northern Mariana Islands', 'جزر ماريانا الشمالية', 0, true),
('nationalite', 'MH', 'Îles Marshall', 'Marshall Islands', 'جزر مارشال', 0, true),
('nationalite', 'PN', 'Îles Pitcairn', 'Pitcairn Islands', 'جزر بيتكيرن', 0, true),
('nationalite', 'SB', 'Îles Salomon', 'Solomon Islands', 'جزر سليمان', 0, true),
('nationalite', 'TC', 'Îles Turques-et-Caïques', 'Turks and Caicos Islands', 'جزر توركس وكايكوس', 0, true),
('nationalite', 'VG', 'Îles Vierges britanniques', 'British Virgin Islands', 'جزر العذراء البريطانية', 0, true),
('nationalite', 'VI', 'Îles Vierges des États-Unis', 'U.S. Virgin Islands', 'جزر العذراء الأمريكية', 0, true),
('nationalite', 'IN', 'Inde', 'India', 'الهند', 0, true),
('nationalite', 'ID', 'Indonésie', 'Indonesia', 'إندونيسيا', 0, true),
('nationalite', 'IQ', 'Irak', 'Iraq', 'العراق', 0, true),
('nationalite', 'IR', 'Iran', 'Iran', 'إيران', 0, true),
('nationalite', 'IE', 'Irlande', 'Ireland', 'أيرلندا', 0, true),
('nationalite', 'IS', 'Islande', 'Iceland', 'آيسلندا', 0, true),
('nationalite', 'IL', 'Israël', 'Israel', 'إسرائيل', 0, true),
('nationalite', 'IT', 'Italie', 'Italy', 'إيطاليا', 0, true),
('nationalite', 'JM', 'Jamaïque', 'Jamaica', 'جامايكا', 0, true),
('nationalite', 'JP', 'Japon', 'Japan', 'اليابان', 0, true),
('nationalite', 'JE', 'Jersey', 'Jersey', 'جيرزي', 0, true),
('nationalite', 'JO', 'Jordanie', 'Jordan', 'الأردن', 0, true),
('nationalite', 'KZ', 'Kazakhstan', 'Kazakhstan', 'كازاخستان', 0, true),
('nationalite', 'KE', 'Kenya', 'Kenya', 'كينيا', 0, true),
('nationalite', 'KG', 'Kirghizistan', 'Kyrgyzstan', 'قيرغيزستان', 0, true),
('nationalite', 'KI', 'Kiribati', 'Kiribati', 'كيريباتي', 0, true),
('nationalite', 'XK', 'Kosovo', 'Kosovo', 'كوسوفو', 0, true),
('nationalite', 'KW', 'Koweït', 'Kuwait', 'الكويت', 0, true),
('nationalite', 'LA', 'Laos', 'Laos', 'لاوس', 0, true),
('nationalite', 'LS', 'Lesotho', 'Lesotho', 'ليسوتو', 0, true),
('nationalite', 'LV', 'Lettonie', 'Latvia', 'لاتفيا', 0, true),
('nationalite', 'LB', 'Liban', 'Lebanon', 'لبنان', 0, true),
('nationalite', 'LR', 'Libéria', 'Liberia', 'ليبيريا', 0, true),
('nationalite', 'LY', 'Libye', 'Libya', 'ليبيا', 0, true),
('nationalite', 'LI', 'Liechtenstein', 'Liechtenstein', 'ليختنشتاين', 0, true),
('nationalite', 'LT', 'Lituanie', 'Lithuania', 'ليتوانيا', 0, true),
('nationalite', 'LU', 'Luxembourg', 'Luxembourg', 'لوكسمبورغ', 0, true),
('nationalite', 'MO', 'Macao', 'Macao', 'ماكاو', 0, true),
('nationalite', 'MK', 'Macédoine du Nord', 'North Macedonia', 'مقدونيا الشمالية', 0, true),
('nationalite', 'MG', 'Madagascar', 'Madagascar', 'مدغشقر', 0, true),
('nationalite', 'MY', 'Malaisie', 'Malaysia', 'ماليزيا', 0, true),
('nationalite', 'MW', 'Malawi', 'Malawi', 'مالاوي', 0, true),
('nationalite', 'MV', 'Maldives', 'Maldives', 'جزر المالديف', 0, true),
('nationalite', 'ML', 'Mali', 'Mali', 'مالي', 0, true),
('nationalite', 'MT', 'Malte', 'Malta', 'مالطا', 0, true),
('nationalite', 'MA', 'Maroc', 'Morocco', 'المغرب', 0, true),
('nationalite', 'MQ', 'Martinique', 'Martinique', 'Martinique', 0, true),
('nationalite', 'MU', 'Maurice', 'Mauritius', 'موريشيوس', 0, true),
('nationalite', 'MR', 'Mauritanie', 'Mauritania', 'موريتانيا', 0, true),
('nationalite', 'YT', 'Mayotte', 'Mayotte', 'مايوت', 0, true),
('nationalite', 'MX', 'Mexique', 'Mexico', 'المكسيك', 0, true),
('nationalite', 'FM', 'Micronésie', 'Micronesia', 'ميكرونيزيا', 0, true),
('nationalite', 'MD', 'Moldavie', 'Moldova', 'مولدوفا', 0, true),
('nationalite', 'MC', 'Monaco', 'Monaco', 'موناكو', 0, true),
('nationalite', 'MN', 'Mongolie', 'Mongolia', 'منغوليا', 0, true),
('nationalite', 'ME', 'Monténégro', 'Montenegro', 'الجبل الأسود', 0, true),
('nationalite', 'MS', 'Montserrat', 'Montserrat', 'مونتسرات', 0, true),
('nationalite', 'MZ', 'Mozambique', 'Mozambique', 'موزمبيق', 0, true),
('nationalite', 'MM', 'Myanmar (Birmanie)', 'Myanmar', 'ميانمار', 0, true),
('nationalite', 'NA', 'Namibie', 'Namibia', 'ناميبيا', 0, true),
('nationalite', 'NR', 'Nauru', 'Nauru', 'ناورو', 0, true),
('nationalite', 'NP', 'Népal', 'Nepal', 'نيبال', 0, true),
('nationalite', 'NI', 'Nicaragua', 'Nicaragua', 'نيكاراغوا', 0, true),
('nationalite', 'NE', 'Niger', 'Niger', 'النيجر', 0, true),
('nationalite', 'NG', 'Nigeria', 'Nigeria', 'نيجيريا', 0, true),
('nationalite', 'NU', 'Niue', 'Niue', 'نييوي', 0, true),
('nationalite', 'NO', 'Norvège', 'Norway', 'النرويج', 0, true),
('nationalite', 'NC', 'Nouvelle-Calédonie', 'New Caledonia', 'كاليدونيا الجديدة', 0, true),
('nationalite', 'NZ', 'Nouvelle-Zélande', 'New Zealand', 'نيوزيلندا', 0, true),
('nationalite', 'OM', 'Oman', 'Oman', 'عمان', 0, true),
('nationalite', 'UG', 'Ouganda', 'Uganda', 'أوغندا', 0, true),
('nationalite', 'UZ', 'Ouzbékistan', 'Uzbekistan', 'أوزبكستان', 0, true),
('nationalite', 'PK', 'Pakistan', 'Pakistan', 'باكستان', 0, true),
('nationalite', 'PW', 'Palaos', 'Palau', 'بالاو', 0, true),
('nationalite', 'PS', 'Palestine', 'Palestine', 'فلسطين', 0, true),
('nationalite', 'PA', 'Panama', 'Panama', 'بنما', 0, true),
('nationalite', 'PG', 'Papouasie-Nouvelle-Guinée', 'Papua New Guinea', 'بابوا غينيا الجديدة', 0, true),
('nationalite', 'PY', 'Paraguay', 'Paraguay', 'باراغواي', 0, true),
('nationalite', 'NL', 'Pays-Bas', 'Netherlands', 'هولندا', 0, true),
('nationalite', 'PE', 'Pérou', 'Peru', 'بيرو', 0, true),
('nationalite', 'PH', 'Philippines', 'Philippines', 'الفلبين', 0, true),
('nationalite', 'PL', 'Pologne', 'Poland', 'بولندا', 0, true),
('nationalite', 'PF', 'Polynésie française', 'French Polynesia', 'بولينزيا الفرنسية', 0, true),
('nationalite', 'PR', 'Porto Rico', 'Puerto Rico', 'بورتوريكو', 0, true),
('nationalite', 'PT', 'Portugal', 'Portugal', 'البرتغال', 0, true),
('nationalite', 'QA', 'Qatar', 'Qatar', 'قطر', 0, true),
('nationalite', 'CF', 'République centrafricaine', 'Central African Republic', 'جمهورية أفريقيا الوسطى', 0, true),
('nationalite', 'DO', 'République dominicaine', 'Dominican Republic', 'جمهورية الدومينيكان', 0, true),
('nationalite', 'CZ', 'République tchèque', 'Czech Republic', 'جمهورية التشيك', 0, true),
('nationalite', 'RE', 'Réunion', 'Réunion', 'لا ريونيون', 0, true),
('nationalite', 'RO', 'Roumanie', 'Romania', 'رومانيا', 0, true),
('nationalite', 'GB', 'Royaume-Uni', 'United Kingdom', 'المملكة المتحدة', 0, true),
('nationalite', 'RU', 'Russie', 'Russia', 'روسيا', 0, true),
('nationalite', 'RW', 'Rwanda', 'Rwanda', 'رواندا', 0, true),
('nationalite', 'EH', 'Sahara occidental', 'Western Sahara', 'الصحراء الغربية', 0, true),
('nationalite', 'BL', 'Saint-Barthélemy', 'Saint Barthélemy', 'سان بارتيلمي', 0, true),
('nationalite', 'KN', 'Saint-Kitts-et-Nevis', 'Saint Kitts and Nevis', 'سانت كيتس ونيفيس', 0, true),
('nationalite', 'SM', 'Saint-Marin', 'San Marino', 'سان مارينو', 0, true),
('nationalite', 'MF', 'Saint-Martin (FR)', 'Saint Martin (FR)', 'سان مارتن', 0, true),
('nationalite', 'SX', 'Saint-Martin (NL)', 'Sint Maarten (NL)', 'سينت مارتن', 0, true),
('nationalite', 'PM', 'Saint-Pierre-et-Miquelon', 'Saint Pierre and Miquelon', 'سان بيير وميكلون', 0, true),
('nationalite', 'VA', 'Saint-Siège (Vatican)', 'Vatican City', 'الفاتيكان', 0, true),
('nationalite', 'VC', 'Saint-Vincent-et-les-Grenadines', 'Saint Vincent and the Grenadines', 'سانت فينسنت والغرينادين', 0, true),
('nationalite', 'SH', 'Sainte-Hélène', 'Saint Helena', 'سانت هيلينا', 0, true),
('nationalite', 'LC', 'Sainte-Lucie', 'Saint Lucia', 'سانت لوسيا', 0, true),
('nationalite', 'SB', 'Salomon', 'Solomon', 'جزر سليمان', 0, true),
('nationalite', 'WS', 'Samoa', 'Samoa', 'ساموا', 0, true),
('nationalite', 'AS', 'Samoa américaines', 'American Samoa', 'ساموا الأمريكية', 0, true),
('nationalite', 'ST', 'Sao Tomé-et-Principe', 'Sao Tome and Principe', 'ساو تومي وبرينسيب', 0, true),
('nationalite', 'SN', 'Sénégal', 'Senegal', 'السنغال', 0, true),
('nationalite', 'RS', 'Serbie', 'Serbia', 'صربيا', 0, true),
('nationalite', 'SC', 'Seychelles', 'Seychelles', 'سيشل', 0, true),
('nationalite', 'SL', 'Sierra Leone', 'Sierra Leone', 'سيراليون', 0, true),
('nationalite', 'SG', 'Singapour', 'Singapore', 'سنغافورة', 0, true),
('nationalite', 'SK', 'Slovaquie', 'Slovakia', 'سلوفاكيا', 0, true),
('nationalite', 'SI', 'Slovénie', 'Slovenia', 'سلوفينيا', 0, true),
('nationalite', 'SO', 'Somalie', 'Somalia', 'الصومال', 0, true),
('nationalite', 'SD', 'Soudan', 'Sudan', 'السودان', 0, true),
('nationalite', 'SS', 'Soudan du Sud', 'South Sudan', 'جنوب السودان', 0, true),
('nationalite', 'LK', 'Sri Lanka', 'Sri Lanka', 'سريلانكا', 0, true),
('nationalite', 'SE', 'Suède', 'Sweden', 'السويد', 0, true),
('nationalite', 'CH', 'Suisse', 'Switzerland', 'سويسرا', 0, true),
('nationalite', 'SR', 'Suriname', 'Suriname', 'سورينام', 0, true),
('nationalite', 'SY', 'Syrie', 'Syria', 'سوريا', 0, true),
('nationalite', 'TJ', 'Tadjikistan', 'Tajikistan', 'طاجيكستان', 0, true),
('nationalite', 'TW', 'Taïwan', 'Taiwan', 'تايوان', 0, true),
('nationalite', 'TZ', 'Tanzanie', 'Tanzania', 'تنزانيا', 0, true),
('nationalite', 'TD', 'Tchad', 'Chad', 'تشاد', 0, true),
('nationalite', 'TF', 'Terres australes françaises', 'French Southern Territories', 'الأراضي الفرنسية الجنوبية', 0, true),
('nationalite', 'IO', 'Territoire britannique de l''océan Indien', 'British Indian Ocean Territory', 'إقليم المحيط الهندي البريطاني', 0, true),
('nationalite', 'TH', 'Thaïlande', 'Thailand', 'تايلاند', 0, true),
('nationalite', 'TL', 'Timor oriental', 'Timor-Leste', 'تيمور الشرقية', 0, true),
('nationalite', 'TG', 'Togo', 'Togo', 'توغو', 0, true),
('nationalite', 'TK', 'Tokelau', 'Tokelau', 'توكيلاو', 0, true),
('nationalite', 'TO', 'Tonga', 'Tonga', 'تونغا', 0, true),
('nationalite', 'TT', 'Trinité-et-Tobago', 'Trinidad and Tobago', 'ترينيداد وتوباغو', 0, true),
('nationalite', 'TN', 'Tunisie', 'Tunisia', 'تونس', 0, true),
('nationalite', 'TM', 'Turkménistan', 'Turkmenistan', 'تركمانستان', 0, true),
('nationalite', 'TR', 'Turquie', 'Turkey', 'تركيا', 0, true),
('nationalite', 'TV', 'Tuvalu', 'Tuvalu', 'توفالو', 0, true),
('nationalite', 'UA', 'Ukraine', 'Ukraine', 'أوكرانيا', 0, true),
('nationalite', 'UY', 'Uruguay', 'Uruguay', 'أوروغواي', 0, true),
('nationalite', 'VU', 'Vanuatu', 'Vanuatu', 'فانواتو', 0, true),
('nationalite', 'VE', 'Venezuela', 'Venezuela', 'فنزويلا', 0, true),
('nationalite', 'VN', 'Vietnam', 'Vietnam', 'فيتنام', 0, true),
('nationalite', 'WF', 'Wallis-et-Futuna', 'Wallis and Futuna', 'واليس وفوتونا', 0, true),
('nationalite', 'YE', 'Yémen', 'Yemen', 'اليمن', 0, true),
('nationalite', 'ZM', 'Zambie', 'Zambia', 'زامبيا', 0, true),
('nationalite', 'ZW', 'Zimbabwe', 'Zimbabwe', 'زيمبابوي', 0, true);

-- Post-seed sanity check : on s'attend à au moins 200 entrées dans la catégorie.
DO $$
DECLARE
  nat_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO nat_count
  FROM core.donnees_referentielles
  WHERE categorie = 'nationalite' AND actif = true;
  IF nat_count < 200 THEN
    RAISE EXCEPTION 'Seed nationalites incomplet : seulement % entrees actives, attendu >= 200', nat_count;
  END IF;
END $$;
